services:
  database:
    image: mongo:latest
    container_name: appservice_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: appservice
      MONGO_INITDB_ROOT_PASSWORD: appservice
